In [1]:
from PIL import Image
import os
from scipy.linalg import eigh
import numpy as np
import pandas as pd

In [32]:
dir = '/Users/ajay/Desktop/IIITA/M.tech_2nd_sem/SOC/assignment_06/pca_dataset/'

In [35]:
i = 0
for file_name in os.listdir(dir):
    print(file_name,i)
    i = i+1
    image = Image.open(dir+'/'+file_name)
    gray_scaled = image.convert('L')
    resized_img = gray_scaled.resize((250,250))
    resized_img.save(file_name)

Arindam_4.jpg 0
Priyo_3.jpg 1
Sumanth_1.jpg 2
Aditya_2.jpg 3
Aditya_3.jpg 4
Mohit_4.jpg 5
Priyo_2.jpg 6
Arindam_5.jpg 7
Sumanth_2.jpg 8
Aditya_1.jpg 9
Sumanth_3.jpg 10
Priyo_1.jpg 11
Arindam_6.jpg 12
Priyo_5.jpg 13
Mohit_3.jpg 14
Aditya_4.jpg 15
Aditya_5.jpg 16
Mohit_2.jpg 17
Priyo_4.jpg 18
Arindam_1.jpg 19
Sumanth_4.jpg 20
Sumanth_5.jpg 21
Mohit_1.jpg 22
Ajay_4.png 23
Ajay_5.png 24
Ajay_2.png 25
IMG_20190306_090206.jpg 26
Ajay_3.png 27
Ajay_1.png 28
Arindam_2.jpeg 29
Arindam_3.jpeg 30


In [34]:
dir1 = '/Users/ajay/Desktop/IIITA/M.tech_2nd_sem/SOC/assignment_06/pca_data_grey/'

In [40]:
def get_data():
    data = []
    i = 0
    name_list = []
    for file_name in os.listdir(dir1):
        print(file_name,i)
        i = i+1
        a = np.array(Image.open(dir1+'/'+file_name))
        #print(len(a))
        data.append(a.flatten())
        name_list.append(file_name)
    return data,name_list

In [41]:
data,names = get_data()

Arindam_4.jpg 0
Priyo_3.jpg 1
Aditya_3.jpg 2
Mohit_4.jpg 3
Arindam_5.jpg 4
Sumanth_3.jpg 5
mohit_7.jpg 6
Arindam_6.jpg 7
Priyo_5.jpg 8
Mohit_3.jpg 9
Aditya_4.jpg 10
Aditya_5.jpg 11
Priyo_4.jpg 12
Sumanth_4.jpg 13
Sumanth_5.jpg 14
Ajay_4.png 15
Ajay_5.png 16
Ajay_3.png 17
Arindam_3.jpeg 18


In [6]:
data = (np.asarray(data)).T

In [7]:
data.shape

(62500, 19)

In [8]:
names[13]

'Sumanth_4.jpg'

In [9]:
def get_mean(data):
    Mean = []
    for rows in data:
        Mean.append(int(rows[0].mean()))
    return np.asarray(Mean)

In [10]:
mean = get_mean(data)

In [11]:
mean = mean.reshape(-1,1)

In [12]:
normalized_data = data - mean

In [13]:
cov = 1/(normalized_data.shape[0]) * np.matmul(normalized_data.T, normalized_data)

In [14]:
eigen_values, eigen_vectors = eigh(cov,eigvals=(17,18))

In [15]:
eigen_values

array([ 11019.83828015, 118446.42382253])

In [16]:
eigen_vectors.shape

(19, 2)

In [17]:
eigen_face = np.matmul(eigen_vectors.T,normalized_data.T)

In [18]:
eigen_face.shape

(2, 62500)

In [19]:
signature = np.matmul(eigen_face,normalized_data)

In [20]:
signature.shape

(2, 19)

In [21]:
pwd

'/Users/ajay/Desktop/IIITA/M.tech_2nd_sem/SOC/assignment_06'

In [22]:
dir2 = '/Users/ajay/Desktop/IIITA/M.tech_2nd_sem/SOC/assignment_06/test_Set_grey/'

In [23]:
for file in os.listdir(dir2):
    image = Image.open(dir2 +'/'+file)
    vec = np.asarray(image)
    vec = vec.flatten()
    vec = vec.reshape(-1,1)
    vec_new = vec - mean
    projected_test_face = np.matmul(eigen_face,vec_new)
    index = []
    for i in range(signature.shape[1]):
        distance = np.sqrt(np.sum((signature[:,i] - projected_test_face)**2))
        index.append(distance)
    #print(np.argmin(index))
    print('predicted = {}, Actual = {}'.format(names[np.argmin(index)],file))
    #print(projected_test_face.shape)

predicted = Mohit_4.jpg, Actual = Sumanth_1.jpg
predicted = Sumanth_5.jpg, Actual = Aditya_2.jpg
predicted = Mohit_4.jpg, Actual = Priyo_2.jpg
predicted = Sumanth_5.jpg, Actual = Sumanth_2.jpg
predicted = Mohit_4.jpg, Actual = Aditya_1.jpg
predicted = Sumanth_5.jpg, Actual = Priyo_1.jpg
predicted = Mohit_4.jpg, Actual = Mohit_2.jpg
predicted = Arindam_4.jpg, Actual = Arindam_1.jpg
predicted = Sumanth_5.jpg, Actual = Mohit_1.jpg
predicted = Mohit_4.jpg, Actual = Ajay_2.png
predicted = Mohit_4.jpg, Actual = Ajay_1.png
predicted = Arindam_4.jpg, Actual = Arindam_2.jpeg


# Face Recognition using LDA

In [27]:
Projected_faces = signature
number_of_class = int(signature.shape[1]/3)

In [91]:
signature.shape

(2, 19)

In [42]:
arindam = [0,4,7,18]
Priyo = [1,8,12]
Aditya = [2,10,11]
Mohit = [3,6,9]
Sumanth = [5,13,14]
Ajay = [15,16,17]

In [94]:
signature[:,arindam].mean(axis = 1)

array([ 1.00736900e+08, -1.10872783e+09])

In [112]:
index = [arindam, Priyo, Aditya, Mohit, Sumanth, Ajay]

[[0, 4, 7, 18], [1, 8, 12], [2, 10, 11], [3, 6, 9], [5, 13, 14], [15, 16, 17]]

In [113]:
np.mean(Projected_faces,axis=1)

array([-1.37727824e+07, -1.58123783e+09])

In [83]:
Projected_face_mean = np.mean(Projected_faces,axis = 1)

In [115]:
def calc_mean(data):
    return signature[:,data].mean(axis=1).reshape(-1,1)

In [103]:
arindam_mean = signature[:,arindam].mean(axis = 1).reshape(-1,1)
sumanth_mean = signature[:,Sumanth].mean(axis = 1).reshape(-1,1)
Priyo_mean = signature[:,Priyo].mean(axis = 1).reshape(-1,1)
Aditya_mean = signature[:,Aditya].mean(axis = 1).reshape(-1,1)
Mohit_mean = signature[:,Mohit].mean(axis = 1).reshape(-1,1)
Ajay_mean = signature[:,Ajay].mean(axis = 1).reshape(-1,1)

In [147]:
def SW(index):
    sum = 0
    for data in index:
        mean = calc_mean(data)
        #print(mean)
        sum += np.matmul((signature[:,data]-mean),(signature[:,data]-mean).T)
        print(sum)
    return sum

In [148]:
within_class = SW(index)

[[ 2.65765407e+16 -1.13944664e+17]
 [-1.13944664e+17  1.91342653e+18]]
[[ 8.13733751e+16 -2.43509607e+17]
 [-2.43509607e+17  2.25232328e+18]]
[[ 9.26361798e+16 -1.84792333e+17]
 [-1.84792333e+17  2.55849974e+18]]
[[ 1.50696672e+17 -3.94784209e+17]
 [-3.94784209e+17  3.31993781e+18]]
[[ 1.84034158e+17 -5.84691976e+17]
 [-5.84691976e+17  4.89776498e+18]]
[[ 2.01770549e+17 -5.75225311e+17]
 [-5.75225311e+17  5.91684306e+18]]


In [155]:
def SB(index):
    sum = 0
    for data in index:
        mean = calc_mean(data)
        sum += np.matmul((mean-Projected_face_mean.reshape(-1,1)),mean.T)
    return sum

In [156]:
between_class = SB(index)

In [161]:
criterion_func = np.matmul(np.linalg.inv(within_class),between_class)

In [163]:
eigen_val,eigen_vec = eigh(criterion_func)

In [164]:
eigen_val

array([0.20187471, 0.62430016])

In [171]:
eigen_vec

array([[ 0.15842163, -0.98737155],
       [-0.98737155, -0.15842163]])

In [174]:
fischer_face = np.matmul(eigen_vec.T,signature)

In [176]:
fischer_face.shape

(2, 19)

In [181]:
for file in os.listdir(dir2):
    image = Image.open(dir2 +'/'+file)
    vec = np.asarray(image)
    vec = vec.flatten()
    vec = vec.reshape(-1,1)
    vec_new = vec - mean
    projected_test_face = np.matmul(eigen_face,vec_new)
    projected_fischer_test_face = np.matmul(eigen_vec.T,projected_test_face)
    print(projected_fischer_test_face.shape)
    print(fischer_face.shape)
    index = []
    for i in range(signature.shape[1]):
        distance = np.sqrt(np.sum((signature[:,i] - projected_test_face)**2))
        index.append(distance)
    #print(np.argmin(index))
    print('predicted = {}, Actual = {}'.format(names[np.argmin(index)],file))
    #print(projected_test_face.shape)

(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Sumanth_1.jpg
(2, 1)
(2, 19)
predicted = Sumanth_5.jpg, Actual = Aditya_2.jpg
(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Priyo_2.jpg
(2, 1)
(2, 19)
predicted = Sumanth_5.jpg, Actual = Sumanth_2.jpg
(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Aditya_1.jpg
(2, 1)
(2, 19)
predicted = Sumanth_5.jpg, Actual = Priyo_1.jpg
(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Mohit_2.jpg
(2, 1)
(2, 19)
predicted = Arindam_4.jpg, Actual = Arindam_1.jpg
(2, 1)
(2, 19)
predicted = Sumanth_5.jpg, Actual = Mohit_1.jpg
(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Ajay_2.png
(2, 1)
(2, 19)
predicted = Mohit_4.jpg, Actual = Ajay_1.png
(2, 1)
(2, 19)
predicted = Arindam_4.jpg, Actual = Arindam_2.jpeg
